### ISSUE TITLE
 Can keep the aspect ratio unchanged ？

### ISSUE THREAD

**Issue by citrusjunoss** [nfroidure/svgicons2svgfont#112]
## Issue

I'm a gentledev i:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked i'm up to date with the latest version of the project

### Expected behavior
```
<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
<title></title>
<g id="icomoon-ignore">
</g>
<path fill="#000" d="M859.022 425.024l-347.022-306.196-347.022 306.196v472.278l264.419-3.762v-166.471c0-45.54 36.918-82.458 82.458-82.458s82.458 36.918 82.458 82.458v166.472l264.709 3.761v-472.278z"></path>
</svg>
```

Original svg    ======       width / height   1 : 1

Converted font  ======     width/height     1: 1

### Actual behavior
Original svg   =======      width / height   1 : 1

Converted font  =======    width/height     ![image](https://user-images.githubusercontent.com/18432488/82797018-0b08a900-9ea9-11ea-98c1-db870194395c.png)

I guess the actual aspect ratio is the aspect ratio of the path

![image](https://user-images.githubusercontent.com/18432488/82797225-5fac2400-9ea9-11ea-8c52-685279695800.png)

### Debugging informations

Node    12.10
Gulp     4.0.2
Gulp-iconfont  10.0.3

**Comment by pioug** [comment]
Please try v10.0.5
