### ISSUE TITLE
Update TypeScript definitions?

### ISSUE THREAD

**Issue by seanking2919** [nfroidure/svgicons2svgfont#129]
I'm not sure who or what's responsible for updating it, but I ran into an issue where I couldn't pass centerVertically into it as I work on a Fantasticon MR. And I found it was due to @types/svgicons2svgfont not having centerVertically. Is there any chance that could be updated? Last update was 9.1.0 according to npm.

**Comment by nfroidure** [comment]
Those declarations are managed by the community in the @types repository, you may PR them to add it.
