### ISSUE TITLE
centerVertically ignore descent

### ISSUE THREAD

**Issue by developer-av** [nfroidure/svgicons2svgfont#135]
### Expected behavior
![image](https://user-images.githubusercontent.com/15675868/132956078-72939fca-26cf-476d-acfc-3d2714850b69.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/15675868/132956096-ca6b81d5-8738-45a8-983e-a67387dd8448.png)

### Steps to reproduce the behavior
```
const fontStream = new SVGIcons2SVGFontStream({
    normalize: false,
    fontHeight: 1000,
    descent: 160,
    centerVertically: true,
});
```
### Debugging informations
- `node -v` result:
```
v14.16.1
```

- `yarn -v` result:
```
1.22.5
```
If the result is lower than 6.9.5, there is
 poor chances i even have a look to it. Please,
 use the last [NodeJS LTS version](https://nodejs.org/en/).

### Use cases

- [x] I will/have implement the feature

**Comment by pioug** [comment]
Thank you! It's in the version 10.0.4
