### ISSUE TITLE
Usage example in readme needs updating after v13.0.0

### ISSUE THREAD

**Issue by anomiex** [nfroidure/svgicons2svgfont#172]
## Issue

I'm a gentledev I:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked I'm up to date with the latest version of the project

### Expected behavior

The documentation at https://github.com/nfroidure/svgicons2svgfont/blob/main/README.md#in-your-scripts accurately reflects how to use the package.

### Actual behavior

The documentation uses `require()`, but since v13.0.0 this package is ESM-only.

### Steps to reproduce the behavior

1. Attempt to create a script based on the example in the readme.

### Debugging informations
- `node -v` result:
```
v22.10.0
```

- `npm -v` result:
```
10.9.0
```
If the result is lower than 20.11.1, there is
 poor chances I even have a look to it. Please,
 use the last [NodeJS LTS version](https://nodejs.org/en/).

**Comment by nfroidure** [comment]
Tahnks for reporting, will try to update asap, feel free to PR if you wish.

**Comment by nfroidure** [comment]
Closed by https://github.com/nfroidure/svgicons2svgfont/commit/04e54a8824d83575c7d4d17537e31c7c7425f83f
