### ISSUE TITLE
Better path bounds calculation

### ISSUE THREAD

**Issue by nfroidure** [nfroidure/svgicons2svgfont#18]
Glyph bounds should be calculed by drawing their pathes with a minimal resolution or maybe a progressive one depending on the path type.

**Comment by evilebottnawi** [comment]
@nfroidure bug with icon 
http://www.filedropper.com/od

**Comment by NaridaL** [comment]
Implemented in https://github.com/nfroidure/svgicons2svgfont/commit/ab900a777c2e61e224eec20902b74262bb60185d . @nfroidure Please give me npm access so I can publish it. (`narida`)
