### ISSUE TITLE
Consider supporting ligatures

### ISSUE THREAD

**Issue by nfroidure** [nfroidure/svgicons2svgfont#19]
cf https://github.com/nfroidure/gulp-iconfont/issues/19

**Comment by nfroidure** [comment]
Shipped with the 2.0.0 release. Breaking compatibility changes though.

**Comment by jouni** [comment]
Hi!

Was this support removed at some point after 2.0? I’m using https://github.com/cognitom/symbols-for-sketch, which uses gulp-iconfont, and at least that doesn’t produce ligatures for the fonts.

**Comment by sabberworm** [comment]
@jouni I guess you could reopen https://github.com/cognitom/symbols-for-sketch/issues/4.

**Comment by jouni** [comment]
Alright, I’ll try my luck there :) Thanks!
