### ISSUE TITLE
Add ability to limit SVG precision / decimal places

### ISSUE THREAD

**Issue by mstorus** [nfroidure/svgicons2svgfont#24]
In order to reduce output SVG font size, can we add the ability to truncate the number of decimal places in the glyph `d` attribute?

For example, my output contains a lot of things like this:
`d=" M666.4 156.39999999999998C681.4 152.39999999999998 686.4 143.39999999999998`
and as a result, the SVG file size is large.

**Comment by nfroidure** [comment]
MErged
