### ISSUE TITLE
Icons inverrsion in font using some icons

### ISSUE THREAD

**Issue by shonny-ua** [nfroidure/svgicons2svgfont#29]
When I use [material-design-icons](http://google.github.io/material-design-icons/) for my font creation all symbols in font are inverted by color.

'Fill' attribute of 'path' tag with a 'none' value in svg file causes this problem.

I fix this symptom locally by replacing:
```
      } else if('path' === tag.name && tag.attributes.d) {
        glyph.d.push(applyTransforms(tag.attributes.d, parents));
      }
```
to
```
      } else if('path' === tag.name && tag.attributes.d && tag.attributes.fill != 'none') {
        glyph.d.push(applyTransforms(tag.attributes.d, parents));
      }
```

Maybe it isn't better way to fix this one. But Your module does not handle the 'fill' attributes.

**Comment by gmetais** [comment]
:+1: 

I have the same problem with icons from the icomoon's downloadable pack (https://icomoon.io/icons.html).
I tried @shonny-ua 's fix and it works fine on my icons!
