### ISSUE TITLE
Support Rounded-Corners (rect rx)

### ISSUE THREAD

**Issue by andremalkine** [nfroidure/svgicons2svgfont#30]
I've noted in your README you state that 'rect' elements are converted to 'path' elements. I've noticed that when using this in conjunction with gulp-iconfont, rectangles with rounded corners come out pointy.

This seems to be because the default SVG output for a rounded rectangle is a `<rect>` element with an `rx="123"` attribute. I'm assuming the rx attribute, which doesn't apply to `<path>` elements, is simply being cast off or ignored. Is there any way to actually translate that value and somehow manipulate the path to reflect the rounded corners?

There are ways to trick your authoring app (Sketch, Illustrator) do handle this conversion for you and export a path, but it can be tricky/annoying for such a common element.

**Comment by maph** [comment]
I'd like to see this as well.

**Comment by nfroidure** [comment]
The rect to path transform is pretty naive and sits here https://github.com/nfroidure/svgicons2svgfont/blob/6ded77da73e92bdf982c60ed1c5188dd648bf24b/src/index.js#L117

Would definitely merge a PR with tests in.
