### ISSUE TITLE
Add option to set additional font metadata

### ISSUE THREAD

**Issue by abrahamvelazquez** [nfroidure/svgicons2svgfont#33]
Most font editors have ways of modifying other metadata. This would help when creating iconfonts that support different weights. 

`font-face font-family="Super Sans" font-weight="bold" font-style="normal"`

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_fonts

`options.fontWeight`
`options.fontStyle`

https://github.com/nfroidure/svgicons2svgfont/blob/master/src/index.js#L258

![screen shot 2015-05-27 at 1 52 54 pm](https://cloud.githubusercontent.com/assets/1004919/7847370/e0fe032e-0477-11e5-9eb3-12aa9215f90d.png)

**Comment by nfroidure** [comment]
Would accept a PR with tests allowing such options.

**Comment by abrahamvelazquez** [comment]
Brilliant! Thank you!
