### ISSUE TITLE
Incorrect Sketch exported svg converting

### ISSUE THREAD

**Issue by Vargentum** [nfroidure/svgicons2svgfont#34]
When I'm converting some icons, exported from Sketch, there is a strange symbols, appeared inside result .ttf file. 
`normalize: true` and `fontHeight: 1001` has been enabled.
Here some links:
Preview: http://screencast.com/t/ddPPIeCUGvGw
Files: https://www.dropbox.com/sh/as0v9yz2cegk6gj/AABT5_JxGx2I30LAOURDrSMTa?dl=0

**Comment by nfroidure** [comment]
Sorry but what am i supposed to notice ?

**Comment by nfroidure** [comment]
Probably related https://github.com/cognitom/symbols-for-sketch/issues/11

**Comment by cognitom** [comment]
@Vargentum I've update the template just now. Check it out ;)

**Comment by Vargentum** [comment]
I've got it! To avoid this issue, you have to export svg icons from Sketch properly.
http://graphicdesign.stackexchange.com/questions/38544/exporting-from-sketch-for-icon-font
```
Prevent SVG from being made out of borders by selecting the path group and clicking on: layer > paths > vectorize stroke
```
