### ISSUE TITLE
Inject custom metadata service

### ISSUE THREAD

**Issue by nfroidure** [nfroidure/svgicons2svgfont#38]
https://github.com/nfroidure/gulp-iconfont/commit/b3f7bbf8324cea7189d691db5c9ab7b86e533bd5#commitcomment-11813660

**Comment by nfroidure** [comment]
Purpose:
In ject a custom metadata service here https://github.com/nfroidure/svgicons2svgfont/blob/master/src/iconsdir.js#L12

Interface: https://github.com/nfroidure/svgicons2svgfont/blob/master/src/metadata.js

Note: The original metadata service can be wrapped to keep its logic as a basis.

**Comment by sabberworm** [comment]
I like the idea.

**Comment by sabberworm** [comment]
Probably we don’t have to make the factory configurable, just the metadata provider function itself.

**Comment by nfroidure** [comment]
Since svgicons2svgfont can only output one font, it may make sense. I have to think about it, may be less future proof, but wn't be the first breaking change of this lib ;).

**Comment by nfroidure** [comment]
Let's go for options.metada being a function((file, cb) and cb(err, metadata) ?

**Comment by nfroidure** [comment]
I'm about to make a new gulp-iconfont / gulp-svgicons2svgfont and svgicons2svgfont release, if any of you wanna PR before, feel free to.

**Comment by sabberworm** [comment]
The option `metadata` is already used for the metadata text in the SVG font file that's why I called it `metadataProvider`. But we could also call it something else, `glyphMetadata` perhaps.

**Comment by nfroidure** [comment]
Completely forgotten that. Also forgotten you already made a PR. Sorry about that, i'm a bit busy currently. Let's go for metadataProvider!
