### ISSUE TITLE
Globbing on Windows

### ISSUE THREAD

**Issue by shammar13** [nfroidure/svgicons2svgfont#39]
Hi

This is an extract of the `scripts` section of my `package.json` file:

``` js
"scripts": {
    "svgicons2svgfont": "svgicons2svgfont --fontname IconFont --output dist/IconFont.svg custom/icons/*.svg"
}
```

Unfortunately, my dev machine is a Windows machine, and I'm finding that when I use globbing (`*.svg`) the script fails. However, when I change the `*.svg` to `iconName.svg` then it works. Unfortunately, this is impractical, because I want to convert all of my SVG icons into an SVG font without having to specify each name individually.

Am I just doing something fundamentally wrong here or is this an issue?

**Comment by nfroidure** [comment]
It is an improvement. Using node-glob somewhere could help, feel free to PR.

**Comment by shammar13** [comment]
I'm not quite sure where to start to add this improvement.

**Comment by nfroidure** [comment]
Except adding node-glob as a dependency, things will sit essentially her https://github.com/nfroidure/svgicons2svgfont/blob/master/bin/svgicons2svgfont.js#L31 for the implementation and there for tests https://github.com/nfroidure/svgicons2svgfont/blob/master/tests/cli.mocha.js#L6

**Comment by shammar13** [comment]
I put a `console.log(program.args)` into the implementation file to see what the file list was looking like before I added `node-glob`.

The output was the complete array of my SVG files - which is correct, and what your module is expecting. However, it isn't writing them to the output file that I am specifying. However, if I list a couple of SVGs as inputs, then it outputs to the destination file perfectly.

It seems like there's a separate issue to the globbing here - what do you think?

(I'm running the script from the Git bash.)

**Comment by nfroidure** [comment]
Can you clone this repo : https://github.com/nfroidure/svgiconfont and run:

```sh
npm i
npm run build
```
And open www/index.html to see if this is your build that fails or also this one that works for me.

**Comment by shammar13** [comment]
Cloned and ran the commands. No luck. I've dumped the output here:

```
> svgiconfont@0.0.1 build_fonts e:\svgiconfont
> mkdirp www/fonts &&  svgicons2svgfont --fontname=iconsfont --appendunicode documents/icons/*.svg > www/fonts/iconsfont.svg && svg2ttf www/fonts/iconsfont.svg www/fonts/iconsfont.ttf && ttf2eot www/fonts/iconsfont.ttf www/fonts/iconsfont.eot && ttf2woff www/fonts/iconsfont.ttf www/fonts/iconsfont.woff && ttf2woff2 < www/fonts/iconsfont.ttf > www/fonts/iconsfont.woff2

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open 'e:\svgiconfont\documents\icons\*.svg'
    at Error (native)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files (x86)\\nodejs\\\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build_fonts"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! svgiconfont@0.0.1 build_fonts: `mkdirp www/fonts &&  svgicons2svgfont --fontname=iconsfont --appendunicode documents/icons/*.svg > www/fonts/iconsfont.svg && svg2ttf www/fonts/iconsfont.svg www/fonts/iconsfont.ttf && ttf2eot www/fonts/iconsfont.ttf www/fonts/iconsfont.eot && ttf2woff www/fonts/iconsfont.ttf www/fonts/iconsfont.woff && ttf2woff2 < www/fonts/iconsfont.ttf > www/fonts/iconsfont.woff2`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svgiconfont@0.0.1 build_fonts script 'mkdirp www/fonts &&  svgicons2svgfont --fontname=iconsfont --appendunicode documents/icons/*.svg > www/fonts/iconsfont.svg && svg2ttf www/fonts/iconsfont.svg www/fonts/iconsfont.ttf && ttf2eot www/fonts/iconsfont.ttf www/fonts/iconsfont.eot && ttf2woff www/fonts/iconsfont.ttf www/fonts/iconsfont.woff && ttf2woff2 < www/fonts/iconsfont.ttf > www/fonts/iconsfont.woff2'.
npm ERR! This is most likely a problem with the svgiconfont package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mkdirp www/fonts &&  svgicons2svgfont --fontname=iconsfont --appendunicode documents/icons/*.svg > www/fonts/iconsfont.svg && svg2ttf www/fonts/iconsfont.svg www/fonts/iconsfont.ttf && ttf2eot www/fonts/iconsfont.ttf www/fonts/iconsfont.eot && ttf2woff www/fonts/iconsfont.ttf www/fonts/iconsfont.woff && ttf2woff2 < www/fonts/iconsfont.ttf > www/fonts/iconsfont.woff2
npm ERR! You can get their info via:
npm ERR!     npm owner ls svgiconfont
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     e:\svgiconfont\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! svgiconfont@0.0.1 build: `mkdirp www && cp documents/html/* www/ && npm run build_js && npm run build_fonts && npm run build_css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svgiconfont@0.0.1 build script 'mkdirp www && cp documents/html/* www/ && npm run build_js && npm run build_fonts && npm run build_css'.
npm ERR! This is most likely a problem with the svgiconfont package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mkdirp www && cp documents/html/* www/ && npm run build_js && npm run build_fonts && npm run build_css
npm ERR! You can get their info via:
npm ERR!     npm owner ls svgiconfont
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     e:\svgiconfont\npm-debug.log
```

Even though I'm running it in the Git bash, it seems like it's still running it as if it's in the normal Windows Command Prompt.

**Comment by nfroidure** [comment]
The Node exec command is probably using the OS shell. Looks like it tries to open the globbing pattern. Did you tried to run 
svgicons2svgfont --fontname=iconsfont --appendunicode documents/icons/*.svg > www/fonts/iconsfont.svg

manuelly, what did it gices ? (create the www folder if it doesn't exist before.

**Comment by shammar13** [comment]
Running it manually worked correctly. It generated the SVG font with all the icons there.

I tried to run it with my icons (I have 44 icons, and the number of icons is growing) and then it failed. I decided to delete icons until the generator worked. The maximum number of icons it would successfully generate was 31 icons.

I tested this within your project too. I removed the unicode at the beginning of each file name, and copied all the files until there were more than 31 files. The SVG font generated incorrectly as well.

**Comment by nfroidure** [comment]
Wierd! Any error outputted ? Did you checked your ulimit -f (or the equivalent in your OS) ? Won't be on any help for Windows since i never used it since a while. Hope someone will be able to help you.

**Comment by shammar13** [comment]
No errors were output. Strangely enough, when I run this module bundled for Grunt (https://github.com/poppinlp/grunt-svgicons2svgfont), then it works with no problems at all.

**Comment by brucecham** [comment]
[Inconsistent appearance in Windows and OSX](https://github.com/nfroidure/gulp-iconfont/issues/115)

**Comment by NaridaL** [comment]
Implemented by https://github.com/nfroidure/svgicons2svgfont/commit/a03780c49f2ab514a55f9e69f95a71cd6dab0bf5 .
