### ISSUE TITLE
CLI silently fails with 32 or more icons

### ISSUE THREAD

**Issue by MrFusion42** [nfroidure/svgicons2svgfont#40]
I'm running into a problem when building a font from several SVG icons.  Here's what I did:

1. Install globally via npm:
    
    ```
    npm install -g svgicons2svgfont
    ```
2. Place any 32 SVG icons in a folder (let's call it `my_icons/`).
3. Build with following command:

    ```
    svgicons2svgfont -v -o out/font.svg my_icons/*.svg
    ```
4. Watch the filesize of `out/font.svg`.  It's **zero bytes!**

If you delete any file from the `my_icons` folder (so that the count is now 31), then the font will be successfully generated.

**Comment by nfroidure** [comment]
Back pressure mechanism was broken. Thanks for reporting that bug.

**Comment by MrFusion42** [comment]
Excellent!  It worked perfectly :+1:
