### ISSUE TITLE
font id vs font family

### ISSUE THREAD

**Issue by idefy** [nfroidure/svgicons2svgfont#41]
It would be great to have an option to define the font id. Currently the font id takes the font-family name.
### Why does this matter ?
When creating a font using [gulp-iconfont](https://github.com/nfroidure/gulp-iconfont) the font file will be the same as the font name. If the font family name has spaces, so will the files generated. This is not always desired for instance on environments that validates there is no space in file namess.

The font id would serve as the font file name.

**Comment by nfroidure** [comment]
Since it is the filename behavior that bother you why not just adding a filename optio to `gulp-svgincons2svgfont` ?

About font id and font family name, i don't really know what difference it makes but I assume to also having the ability to set it separately won't hurt.

Would accept a PR doing so.

**Comment by idefy** [comment]
Thanks for replying so quickly.

- Font id are used to build URI references, see [here how it can be used](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_fonts). 
- Also most font web libraries use the font id as a unique identifier for their databases, whereas the font family name is the display name.[example on font.com](http://www.fonts.com/web-fonts/developers/api/add-font)
- Finally, and I know this is not really the intent of the code but, providing a same font-family name but different IDs make sense when you create several fonts for bold, italic, etc.. under a same family [see here for the clean way to declare family name in css](http://www.456bereastreet.com/archive/201012/font-face_tip_define_font-weight_and_font-style_to_keep_your_css_simple/). 

Hence why I think ID makes a good fit to be used as the file name rather than the font family.

I will see if I have time to make a PR on monday as you've suggested, but I still believe more control should be given between the ID and the name of a font.

**Comment by idefy** [comment]
I have made a PR for font Id and also another PR on gulp-svgincons2svgfont for filename as suggested.

**Comment by nfroidure** [comment]
Thanks for your contribution. Unfortunately, it comes with no test wich means that i'll have to do them at merge. So i can't guarantee you when i'll have time to do it.

If you are in a hurry, please add some tests and i'll merge and publish asap.

**Comment by nfroidure** [comment]
https://github.com/nfroidure/svgicons2svgfont/pull/42
https://github.com/nfroidure/gulp-svgicons2svgfont/pull/28

**Comment by idefy** [comment]
I will try to make a test case or two. I am new at mocha, so may also take me some time to get to it, but will try my best.

Note that on windows several mocha tests fail. Also the `npm test` doesn't work under windows, I have to run with mocha installed globaly and change npm test value to : "mocha tests/*.mocha.js". But I should probably open a separate issue for this with some details.

**Comment by idefy** [comment]
Ok, I have added the test against the filename option.

**Comment by nfroidure** [comment]
Tests should be in the nearest module, i added a fontId test to svgicons2svgfont for that matter.

Otherwise, you made a clean and valuable contribution.

Thank you! :+1:
