### ISSUE TITLE
Arcs rendering in the wrong direction

### ISSUE THREAD

**Issue by tremby** [nfroidure/svgicons2svgfont#44]
The following glyph should have a ring rather than a sort of concave diamond.

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" x="0px" y="0px" viewBox="0 0 500 500" width="500" height="500">
	<path style="fill:#000000;stroke:none;stroke-width:2.5;stroke-linecap:butt;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none" d="M 250 0 A 250 250 0 0 0 0 250 A 250 250 0 0 0 250 500 A 250 250 0 0 0 500 250 A 250 250 0 0 0 250 0 z M 250 29.513672 A 220.48656 220.48656 0 0 1 470.48633 250 A 220.48656 220.48656 0 0 1 250 470.48633 A 220.48656 220.48656 0 0 1 29.513672 250 A 220.48656 220.48656 0 0 1 250 29.513672 z "/>
</svg>
```

I suspect the problem is that the arc components of the first path are handled incorrectly. In particular, the `sweep-flag` is being treated the opposite way from how it should, at least in all cases of this particular glyph.

Here's another example, loosely based on [one of the examples](http://www.w3.org/TR/SVG/images/paths/arcs02.svg) in the [arc segments section of the SVG spec](http://www.w3.org/TR/SVG/paths.html#PathDataEllipticalArcCommands), and has all possible combinations of `large-arc-flag` and `sweep-flag`:

The following glyph

```svg
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="500" height="500" viewBox="0 0 500 500" version="1.1" xmlns="http://www.w3.org/2000/svg">
  <path d="M0,250 l20,0 a40,20 0 0,0 40,20 l80,-20 a40,20 0 0,1 40,20 l80,-20 a40,20 0 1,0 40,20 l80,-20 a40,20 0 1,1 40,20 l80,-20 l0,-120 H0 Z" />
</svg>
```

Renders before going through svgicons2svgfont as this (correct):
![screen shot 2015-09-30 at 21 45 21](https://cloud.githubusercontent.com/assets/199635/10213090/773d8532-67bd-11e5-83f5-357af786b665.png)

but after svgicons2svgfont as this:
![screen shot 2015-09-30 at 21 45 30](https://cloud.githubusercontent.com/assets/199635/10213098/853c88f4-67bd-11e5-96c5-1137fbad8195.png)

This is consistent with the `sweep-flag` being reversed.

I did more tests with each arc rotated by 30 degrees, -30 degrees, and with arcs drawn along an otherwise straight line and I see the same issue in all cases.

**Comment by nfroidure** [comment]
Hi! Thanks for reporting. Did you test the font rendering directly with the SVG font or via the TTF one?

**Comment by tremby** [comment]
I tested with TTF and WOFF in Chrome, but couldn't coax it into rendering the SVG. For the screenshots above I imported the source SVG and the output font SVG into Icomoon. I saw the same incorrect output in all cases except the source SVG.

**Comment by nfroidure** [comment]
Opened the produced font with sourceforge and found the problem also sits in SVG fonts. I'm looking at fixing it.

**Comment by nfroidure** [comment]
The problem sit in SVGPathData, it is fixed now. You'll have to reinstall svgicons2svgfont to get the last SVGPathData version bundled with it.

The fix https://github.com/nfroidure/SVGPathData/commit/179416d7ed7cbb7a5e4417a89b9528e865e31932
