### ISSUE TITLE
Pixel-accurate size lead to errors

### ISSUE THREAD

**Issue by dreerr** [nfroidure/svgicons2svgfont#47]
When working with a SVG from Illustrator, having it set to 120x180px canvas size the corresponding glyph has errors. When upscaling the canvas to 1200x1800px with the artwork resized the problem is gone.
Already tried changing the _round_ parameter.

here is a screenshot of the result, zoomed in:
<img width="565" alt="bildschirmfoto 2015-12-16 um 14 12 48" src="https://cloud.githubusercontent.com/assets/1454661/11841679/35eee70a-a3ff-11e5-8200-62925edc1cac.png">

**Comment by nfroidure** [comment]
This is a know TTF limitation, see https://github.com/nfroidure/gulp-iconfont#preparing-svgs to find the best practices for preparing your SVG files.

**Comment by dreerr** [comment]
Thanks a lot and sorry for bothering :(

**Comment by nfroidure** [comment]
No problem, it would be best if it were mentioned in this repo's readme too.
