### ISSUE TITLE
Custom Metadata

### ISSUE THREAD

**Issue by bm2u** [nfroidure/svgicons2svgfont#50]
@nfroidure:
Hi, I am currently working with the metadata option to mention the current version and further vendor details. Unfortunately the meta-information of the font itself differs from my custom metata. Is it possible to change these attributes as seen on the screenshot (e.g. fontVersion, fontDescriptor, fontVendorUrl)? 

![iconfont](https://cloud.githubusercontent.com/assets/11159476/12888360/0171242a-ce7a-11e5-9f5a-b00c72e18eba.png)

BTW: I am using gulp-iconfont for the entire workflow.

**Comment by willpracht** [comment]
I'm curious about this as well.

Was there ever a resolution?

If so, can we maybe provide an example of how to pass that information in?

**Comment by bm2u** [comment]
@willpracht please refer to https://github.com/nfroidure/gulp-iconfont/issues/111
