### ISSUE TITLE
Circle and Ellipse Fill Conversion Inverted

### ISSUE THREAD

**Issue by devnopt** [nfroidure/svgicons2svgfont#53]
The Circle and Ellipse shapes appear not to work when the shape is an outline.

The following will produce a filled ellipse when it should only be an outline:

<ellipse fill="#FFFFFF" stroke="#000000" stroke-width="1" cx="16" cy="13" rx="9" ry="8"/>

Is this a limitation when converting to a font?

**Comment by nfroidure** [comment]
Please provide the concerned icon and the version you're currently using.

**Comment by devnopt** [comment]
Was able to resolve the issue by converting the ellipse to paths.

Note that I am using gulp-iconfont version 6.0.0, which recommended that I write the issue here.
