### ISSUE TITLE
Please remove log

### ISSUE THREAD

**Issue by arwidt** [nfroidure/svgicons2svgfont#58]
Hello.

I would really appreciate it if you could remove the "Fonts created" log in the index.js file, or add a verbose flag or something.

Best regards.

**Comment by nfroidure** [comment]
You can do it programmatically here https://github.com/nfroidure/svgicons2svgfont#optionslog by passing a noop function.

**Comment by arwidt** [comment]
Great, thanks. Sorry for not reading the docs :)
