### ISSUE TITLE
Font icons are Jumbled occationaly

### ISSUE THREAD

**Issue by Srividya1790** [nfroidure/svgicons2svgfont#59]
I am using gulp-iconfont-css and gulp-iconfont to create font icon from SVG. Occasionaly the font icons are jumbled/Empty on first load of the website.

**Comment by sabberworm** [comment]
Are there any errors in the browser console?

**Comment by pete-hotchkiss** [comment]
realise this is an old thread - but I'm seeing what I think will be similar behaviour 

![image](https://cloud.githubusercontent.com/assets/16895748/23661173/cea6982c-0343-11e7-90b2-0d7e1ae1ac61.png)
Is the font

Generated from a SVG file like so

![image](https://cloud.githubusercontent.com/assets/16895748/23661193/e2db69ee-0343-11e7-83d1-b5a5b07a8d08.png)

**Comment by pesimeao** [comment]
I have the same problem. 

![image](https://cloud.githubusercontent.com/assets/2428395/23949726/591222a0-0980-11e7-835d-83346f77222e.png)

Original:
![image](https://cloud.githubusercontent.com/assets/2428395/23949760/7356a744-0980-11e7-9b71-63a72f56e754.png)

**Comment by nfroidure** [comment]
Did you try https://github.com/nfroidure/svgicons2svgfont/issues/61

**Comment by pesimeao** [comment]
@nfroidure it worked ;)
I had to generate my svg files with 120px minimum size.
Thanks!
