### ISSUE TITLE
Icons displaying incorrectly

### ISSUE THREAD

**Issue by Youssefsh** [nfroidure/svgicons2svgfont#61]
I'm not sure what information i need to post here to figure this out, But i'm using gulp-iconfont to create my icon font and on their repo description, they mentioned that if there's a problem with displaying the icons i should open an issue here. 

Image example:
![image](https://cloud.githubusercontent.com/assets/5422171/18800891/f00631ac-81df-11e6-890a-4e85b1f261f4.png)

**Comment by nfroidure** [comment]
Your SVGs are probably too small, you should play with https://github.com/nfroidure/svgicons2svgfont#optionsfontweight
https://github.com/nfroidure/svgicons2svgfont#optionsnormalize

or scale them up.
