### ISSUE TITLE
Invalid / corrupted woff2 ?

### ISSUE THREAD

**Issue by lossius30** [nfroidure/svgicons2svgfont#63]
Hi, 
After executing the command "svgicons2svgfont --fontname=TestFont --fontId=TestFont --weight=400 --prependUnicode --output=/output/ /my/svg/files/*.svg" i get my .SVG font file.

After this I convert the SVG to TTF and then TTF to WOFF2.

But there is a problem with the WOFF2 (the TTF works fine and display glyphs), firefox says :

downloadable font: Failed to convert WOFF 2.0 font to SFNT (font-family: "TestFont" style:normal weight:normal stretch:normal src index:0) source: http://fonts.wdx.fr/TestFont.woff2

downloadable font: rejected by sanitizer (font-family: "TestFont" style:normal weight:normal stretch:normal src index:0) source: http://fonts.wdx.fr/TestFont.woff2

Same on chrome... Any idea ??

**Comment by nfroidure** [comment]
Closing since not related to this module.
