### ISSUE TITLE
using inside of a batch file, eliminating wildcard?

### ISSUE THREAD

**Issue by mspanish** [nfroidure/svgicons2svgfont#66]
Awesome script! I can use it great from the CLI, but I'd rather loop over a bunch of directories using a .bat file - but the wildcard stops it in its tracks. Is it really necessary? Can't you just specify a folder and be done w/ it? I am looking through your source code but as a Node.js moron I'm not sure where to eliminate the need for this.

**Comment by sabberworm** [comment]
I think the wildcard is evaluated by the shell, not by svgicons2svgfont.

So the following:

```bash
svgicons2svgfont --fontname=hello -o font/destination/file.svg icons/directory/*.svg
```

is equivalent to

```bash
svgicons2svgfont --fontname=hello -o font/destination/file.svg icons/directory/file1.svg icons/directory/file3.svg icons/directory/file2.svg
```

Assuming `file1.svg`, `file2.svg` and `file3.svg` are the only three files in `icons/directory/`.

So you can easily (maybe knowing the limited capabilities of batch scripts, it won’t be so easy after all… I’d probably rather use PowerShell, bash or zsh) write a batch script that searches the files you want added and adds them to the list of arguments.

**Comment by mspanish** [comment]
thanks a lot for your fast reply!- I have way too many files, actually I found a really simple solution - just create a text file listing the command for the specific folder w/ the wildcard - then I just pasted all of those commands and it ran all of the folders 1 by 1.
