### ISSUE TITLE
stopped writing .svg files

### ISSUE THREAD

**Issue by mspanish** [nfroidure/svgicons2svgfont#67]
Hello I've installed some other stuff like Ruby and more npm modules -and all of the sudden my svgicons2svgfont doesn't output files anymore - it just prints to the console. Any idea what I need to do to get it to output files? I haven't changed my command, for example:

`svgicons2svgfont --fontname=geom -0 geom.svg geom/*.svg `

**Comment by nfroidure** [comment]
Late in the game but you wrote a `0` instead of a `O` ;).

**Comment by mspanish** [comment]
thanks a lot, better late than never :)
