### ISSUE TITLE
Font glyphs aren't converted properly and are pretty worse comparing with their SVG icons.

### ISSUE THREAD

**Issue by gladisihor** [nfroidure/svgicons2svgfont#70]
Font glyphs aren't converted properly and are pretty worse comparing with their SVG icons.
I wrote normalize:true and fontHeight: 1001 in the gulp options, but it didn't resolve my problem at all...

![fonts issue](https://user-images.githubusercontent.com/15730570/27277130-e99bece2-54e5-11e7-816b-22bdb791c85d.jpeg)
![gulp options](https://user-images.githubusercontent.com/15730570/27277455-f8571bde-54e6-11e7-8110-c8010baf928b.png)

**Comment by ggirou** [comment]
I had the same problem with default options.
I only set `fontHeight: 1000` to fix it.

**Comment by NaridaL** [comment]
@gladisihor Are you still having issues with the latest version?

**Comment by NaridaL** [comment]
I'm closing this as there's been no further comments, if you do have an issue feel free to open a new issue.

**Comment by NaridaL** [comment]
@xlcs0110 Without a sample of the icons you are converting and your configuration there is not much we can do.
