### ISSUE TITLE
Icons not generated properly

### ISSUE THREAD

**Issue by aseem2625** [nfroidure/svgicons2svgfont#73]
I'm taking icons from [materials website](https://material.io/icons/#ic_search) of 42dp.
My gulp task is below:
```

// Gulp task to generate font icons from svg (run: gulp iconfont)
const fontName = 'icons';
gulp.task('iconfont', function() {
  gulp
    .src(['some_path/svgs/*.svg'])
    .pipe(
      iconfontCss({
        fontName: fontName,
        targetPath: 'style.css',
        fontPath: './',
        cssClass: 'icon',
      })
    )
    .pipe(
      iconfont({
        fontName: fontName,
        formats: ['svg', 'ttf', 'eot', 'woff', 'woff2'], // default, 'woff2' and 'svg' are available
        normalize: true,
        prependUnicode: true, // recommended option
        fontHeight: 1001, // Tried lot of values, <1000 and also 10000, and 100000 :P but no success
        centerHorizontally: true,
      })
    )
    .pipe(gulp.dest('some_path/styles/fonts/'));
});


```
As the documentation says,
![image](https://user-images.githubusercontent.com/6055628/28070991-5a73149e-666c-11e7-8578-b864ea35f050.png)
![image](https://user-images.githubusercontent.com/6055628/28071006-65dadad8-666c-11e7-8b42-1419c795051f.png)

But the fonts generated aren't proper. font
![image](https://user-images.githubusercontent.com/6055628/28070969-47e710d2-666c-11e7-9b20-1d27c5680387.png)

And my expecting fonts should look like obviously not with extra space because I'm giving `normalize: true` and `fontHeight: 1001`
This below I got from [iconmoon](https://icomoon.io/) website and this is how I am expecting
![image](https://user-images.githubusercontent.com/6055628/28072957-087c952e-6672-11e7-831e-9fa78405a1f4.png)

Linking to [issue](https://github.com/nfroidure/gulp-iconfont/issues/146)

**Comment by nfroidure** [comment]
The problem sits in this RegExp I think: https://github.com/nfroidure/svgicons2svgfont/blob/master/src/index.js#L60

**Comment by aseem2625** [comment]
Hey @nfroidure 
Thanks for pointing that out. But looks correct to me.
For `<svg fill="#000000" height="48" viewBox="0 0 24 24" width="48"`  It's splitting fine. Ain't it?
<img src="https://user-images.githubusercontent.com/6055628/28159838-edf5f37e-67db-11e7-885e-4dba52c2dc1c.png" width=270/>

**Comment by nfroidure** [comment]
Hum, right. The problem may be that the width/height should be computed from the width/height and viewBow attribute somewhere there: https://github.com/nfroidure/svgicons2svgfont/blob/master/src/index.js#L186-L210

**Comment by aseem2625** [comment]
@nfroidure 
I think you're right, it's probably due to this piece of code,
https://github.com/nfroidure/svgicons2svgfont/blob/master/src/index.js#L191-L203

**Comment by aseem2625** [comment]
So, I think I got the issue
@nfroidure 
I feel that this code shouldn't exist https://github.com/nfroidure/svgicons2svgfont/blob/master/src/index.js#L198-L203

Instead if you're considering width and height at all, then that can be used as scale factor and not for clipping which is why the size of icon generated is coming more than size of actual icon.

Like, in this case, actual font is  (24,24) (since starting is 0,0) but it's actual width,height is 48,48 which is scaling from (24,24) and not clipping area.

I think, my explanation is correct bcoz when I open this .svg in inkscape, it opens correctly to the size 48x48. And when I modify values of svg to `height="24" viewBox="0 0 24 24" width="24" `
this library works fine in converting to icon.

We can discuss about modifying once you think it's fine.

**Comment by nfroidure** [comment]
Was actually a duplicate of https://github.com/nfroidure/svgicons2svgfont/issues/9
