### ISSUE TITLE
sh: metapak: command not found

### ISSUE THREAD

**Issue by GitScrum** [nfroidure/svgicons2svgfont#75]
Hi, i get this after install

```bash
> svgicons2svgfont@7.0.0 postinstall /Users/ivandemidov/Project/test-svgf/node_modules/svgicons2svgfont
> npm run metapak --silent

sh: metapak: command not found
```

**Comment by nfroidure** [comment]
@GitScrum thanks for reporting. This is due to an early `metapak` version, I will update it when its v1 will be definitely released. In the meanwhile, you can just ignore it since it has no impact at all on the plugin for their users.

**Comment by GitScrum** [comment]
@nfroidure Thanks, i will wait at news.
