### ISSUE TITLE
Shape becomes solid

### ISSUE THREAD

**Issue by oscar-broman** [nfroidure/svgicons2svgfont#77]
### Expected behavior

It should render the shape hollow inside.

### Actual behavior

It becomes solid and any contents are subtracted.

### Steps to reproduce the behavior

Render this into a font: http://svgshare.com/i/3QB.svg ([here](http://nfroidure.github.io/svgiconfont/)).

**Comment by NaridaL** [comment]
The issue is that the triangular outline is a single path with a stroke width and no fill. svgicons2svgfont has afaik always interpreted paths as outlines of shapes. You need to convert strokes to paths. See https://github.com/nfroidure/svgicons2svgfont/issues/60 for a way of automating that.

**Comment by oscar-broman** [comment]
I see. Thanks! I'll close this as it's essentially a duplicate of #60.
