### ISSUE TITLE
Using geometry-interfaces

### ISSUE THREAD

**Issue by trusktr** [nfroidure/svgicons2svgfont#79]
Hello, I'm the author of the [geometry-interfaces polyfill](https://github.com/trusktr/geometry-interfaces). I saw this package depending on geometry-interfaces. I'm curious to know: what are you using geometry-interfaces for? Is there any way I can help? - Joe

**Comment by NaridaL** [comment]
@trusktr Sorry, that's a mistake on my part. I needed a matrix implementation and considered your package at one point, but didn't end up using it. Looks like I accidentally added it to the dependencies.

**Comment by trusktr** [comment]
Ah, no prob.
