### ISSUE TITLE
normalize parameter could lead to font file icons size differ

### ISSUE THREAD

**Issue by qingbolove** [nfroidure/svgicons2svgfont#83]
I just checked the normalize definition, it is : change icons by scaling them to the height of the highest icon.
But actually I want to change their size according to their relative size, not highest for everyone.
For example, this is what I expected:
![image](https://user-images.githubusercontent.com/10628904/35211481-7421afee-ff0b-11e7-9066-9d0cb9a0f19d.png)

But after use normalization, I got:
![image](https://user-images.githubusercontent.com/10628904/35211459-61d6cac2-ff0b-11e7-9854-bc40bcc4aa4b.png)

Is there a workaround for me to get a relative height for several svg files?

**Comment by NaridaL** [comment]
Is increasing the font-size where you use the font not an option to uniformly scale the glyphs? Why do you want to change the size of the glyphs here?

**Comment by NaridaL** [comment]
@qingbolove The latest version now scales the icons according to fontHeight even when normalize is false. This should be what you needed.
